apiVersion: 1

datasources:
  - name: Cortex
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cortex:8009/prometheus
    version: 1
    basicAuth: false
    editable: true
    isDefault: true
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    version: 1
    basicAuth: false
    editable: true
    isDefault: false
