apiVersion: 1

datasources:
  - name: Cortex
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cortex/prometheus
    version: 1
    basicAuth: false
    editable: true
    isDefault: true
