# my global config
global:
  scrape_interval: 1s

remote_write:
  - url: http://cortex:8009/api/v1/push
    send_exemplars: false
    send_native_histograms: true
    #headers:
      #X-Scope-OrgID: user1

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "app"
    static_configs:
    - targets: ["native-histogram-demo:18080"]

